# Generated by Django 4.2.5 on 2023-10-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=12)),
                ('sector', models.CharField(max_length=100)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('public_date', models.DateField()),
                ('settlement_month', models.CharField(max_length=10)),
                ('ceo_name', models.CharField(blank=True, max_length=50, null=True)),
                ('homepage', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
