# Generated by Django 3.2.16 on 2023-03-01 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('period_unit', models.CharField(blank=True, choices=[('Y', 'Year'), ('M', 'Month'), ('D', 'Day')], max_length=1, null=True)),
                ('rebalancing_period', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('ticker_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, choices=[('KR', 'KR'), ('US', 'US')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateTimeField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=14, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=14, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=14, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=14, null=True)),
                ('adj_close_price', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=14, null=True)),
                ('volume', models.IntegerField(blank=True, default=None, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=14, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_price', to='stock.stock')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='stock.stockmarket'),
        ),
        migrations.CreateModel(
            name='PortfolioStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio', to='stock.portfolio')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='stock.stock')),
            ],
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['stock', 'stock_date'], name='stock_stock_stock_i_10ac19_idx'),
        ),
    ]
