# Generated by Django 4.2.7 on 2023-12-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('report', models.CharField(choices=[('11013', 'Q1'), ('11012', 'Q2'), ('11011', '1 YEAR'), ('11014', 'Q3')], max_length=5)),
                ('fs_div', models.CharField(choices=[('OFS', '재무제표'), ('CFS', '연결재무제표')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_financial_state', to='stock.company')),
            ],
        ),
        migrations.CreateModel(
            name='Ratios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_count', models.BigIntegerField(blank=True, null=True)),
                ('preference_share_count', models.BigIntegerField(blank=True, null=True)),
                ('eps', models.IntegerField(blank=True, null=True)),
                ('roe', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratios', to='stock.financialstate')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_Revenue', models.BigIntegerField(blank=True, null=True)),
                ('net_income', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_statement', to='stock.financialstate')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('total_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('total_equity', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_sheet', to='stock.financialstate')),
            ],
        ),
    ]
