# Generated by Django 4.2.7 on 2024-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockprice_eps_stockprice_pbr_stockprice_per_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='moving_average_120',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='moving_average_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='moving_average_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='moving_average_60',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialstate',
            name='report',
            field=models.CharField(choices=[('11012', 'Q2'), ('11011', '1 YEAR'), ('11013', 'Q1'), ('11014', 'Q3')], max_length=5),
        ),
    ]
