version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/work/mint-server
hooks:
  BeforeInstall:
   - location: scripts/before_install.sh
     runas: root
  Install:
   - location: scripts/install.sh
     runas: root
  ApplicationStart:
   - location: scripts/application_start.sh
     runas: root
